name: file_transfer
description: "Zero SPOF file transfer over Nostr. E2E encrypted, decentralized, and private."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  crypto: ^3.0.7
  cryptography: ^2.9.0
  desktop_drop: ^0.7.0
  file_picker: ^10.3.10
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_dropzone: ^4.2.1
  get: ^4.7.3
  mime: ^2.0.0
  ndk: ^0.7.1-dev.19
  ndk_flutter: ^0.0.2-dev.13
  nip49: ^1.1.2
  path: ^1.9.1
  toastification: ^3.0.3
  file_transfer_sdk:
    path: packages/file_transfer_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
