name: file_transfer_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  cryptography: ^2.9.0
  ndk: ^0.7.1-dev.19
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
